### ISSUE TITLE
Error importing project in Android studio

### ISSUE THREAD

**Issue by Sam1301** [udacity/ud839_CustomAdapter_Example#1]
The project cannot be imported in Android Studio due to the following error:

> Cannot find file ../ud839_CustomAdapter_Example/settings.jar

**Comment by ghost** [comment]
@Sam1301 No Error, Working fine. Try this File> New > Project from Version Control > GitHub

P.S.:- Don't forgot to fork the repository.

**Comment by DoppaHarish** [comment]
i copied the same code and pasted in my new project but it shows a white screen.Why this happen?

**Comment by lfsabcd7** [comment]
does not contain build.gradle (Project) TopLevel gradle file missing

**Comment by AbeEtan** [comment]
Hello I am getting this error
Could not initialize class com.android.sdklib.repositoryv2.AndroidSdkHandler

**Comment by SudKul** [comment]
I know we're late. 
But, we've updated the App to support AndroidX in this [commit](https://github.com/udacity/ud839_CustomAdapter_Example/commit/771f0033aa7b3e39a752926969fee0a445f9c29a). Try using the updated code, and hopefully, you won't find any issues. 

Besides, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
