### ISSUE TITLE
Unable to see the listview items

### ISSUE THREAD

**Issue by saiprajoth** [udacity/ud839_CustomAdapter_Example#14]
app is running without any crashes and even the listview layout is visible on the screen, but textview items are not being visible. please do help me out

**Comment by SudKul** [comment]
Hey @Sai-8919 
We've updated the App to support AndroidX in this [commit](https://github.com/udacity/ud839_CustomAdapter_Example/commit/771f0033aa7b3e39a752926969fee0a445f9c29a). Try using the updated code, and hopefully, you won't find any issues. 

Besides, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
