### ISSUE TITLE
The App Crashes

### ISSUE THREAD

**Issue by MSaeed-Sudo** [udacity/ud839_CustomAdapter_Example#9]
![Screenshot from 2020-04-18 17-59-21](https://user-images.githubusercontent.com/45807900/79642554-6951b600-819e-11ea-9ff5-d2a159faa3dc.png)
I'm using this approach and no errors claim however the app crashes every time i press the textview
any ideas??

**Comment by SudKul** [comment]
I know, we're late. 
But, we've updated the App to support AndroidX in this [commit](https://github.com/udacity/ud839_CustomAdapter_Example/commit/771f0033aa7b3e39a752926969fee0a445f9c29a). Try using the updated code, and hopefully, you won't find any issues. 

Besides, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
